package com.ventas.main;

import com.ventas.frame.AbmArticulosPorMontoFrame;
import com.ventas.frame.AbmClienteFrame;
import com.ventas.frame.AbmFacturasComprasFrame;
import com.ventas.frame.AbmProductoFrame;
import com.ventas.frame.AbmProductosInactivosFrame;
import com.ventas.frame.AbmProductosTopFrame;
import com.ventas.frame.AbmProductosTopInactivosFrame;
import com.ventas.frame.AbmRubroFrame;
import com.ventas.frame.AbmStockFrame;
import com.ventas.frame.AbmSubRubroFrame;
import com.ventas.frame.AbmTipoDocForm;
import com.ventas.frame.BackupFrame;
import com.ventas.frame.DuplicadoFacturaFrame;
import com.ventas.frame.DuplicadoFacturaPdfFrame;
import com.ventas.frame.FacturaWebFrame;
import com.ventas.frame.FacturaWebPanificadosFrame;
import com.ventas.frame.FacturarFrame;
import com.ventas.frame.ArticulosConSaldoPendienteParaAsignarFrame;
import com.ventas.frame.FacturasDeMercadoPagoFrame;
import com.ventas.frame.FacturasMercadoPagoCompletadasFacturarFrame;
import com.ventas.frame.FacturarMercadoPagoFrame;
import com.ventas.frame.FacturasMercadoPagoPendientesFacturarFrame;
import com.ventas.frame.ImportarClientesMercadoPagoFrame;
import com.ventas.frame.ImportarProductoFrame;
import com.ventas.frame.InformeStockFrame;
import com.ventas.frame.InformeVentasPorPeriodoFrame;
import com.ventas.frame.ModificarConfiguracionTopFrame;
import com.ventas.frame.NotaCreditoFrame;
import com.ventas.frame.RecuperarDeAfipFrame;
import com.ventas.frame.RemitoFrame;
import com.ventas.frame.RemitoPanificadosFrame;
import com.ventas.frame.StockPeriodoProductoCompraFrame;
import com.ventas.frame.StockPeriodoProductoFrame;
import com.ventas.frame.VerificarAfipFrame;
import com.ventas.services.FacturaService;
import com.ventas.services.FcService;
import com.ventas.services.RenglonFcService;
import java.io.File;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 100, 255));
        this.setLocationRelativeTo(null);
//        duplicadoPdfMnu.setVisible(false);
        recuperarAfipMnu.setVisible(true);
        clientesMnu.setVisible(false);
        tipoDocMnu.setVisible(false);
        notaCreditoBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirBtn = new javax.swing.JButton();
        randomBtn = new javax.swing.JButton();
        notaCreditoBtn = new javax.swing.JButton();
        facturaMercadoPagoBtn = new javax.swing.JButton();
        facturaAutomPorImporteBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        configuracionMnu = new javax.swing.JMenuItem();
        productosMnu = new javax.swing.JMenuItem();
        verInactivosMnu = new javax.swing.JMenuItem();
        productosUtilizadosMnu = new javax.swing.JMenuItem();
        productosTopInactivosMnu = new javax.swing.JMenuItem();
        rubrosMnu = new javax.swing.JMenuItem();
        subRubrosMnu = new javax.swing.JMenuItem();
        clientesMnu = new javax.swing.JMenuItem();
        tipoDocMnu = new javax.swing.JMenuItem();
        stockMnu = new javax.swing.JMenuItem();
        comprasPorImporteMnu = new javax.swing.JMenuItem();
        articulosPorMontoMnu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verificarAfipMnu = new javax.swing.JMenuItem();
        recuperarAfipMnu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        backupMnu = new javax.swing.JMenuItem();
        duplicadoPdfMnu = new javax.swing.JMenuItem();
        importarMnu = new javax.swing.JMenuItem();
        importarMercadoPagoMnu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ventasPorPeriodoMnu = new javax.swing.JMenuItem();
        informeStockMnu = new javax.swing.JMenuItem();
        stockPeriodoProductoVentaMnu = new javax.swing.JMenuItem();
        stockPeriodoProductoCompraMnu = new javax.swing.JMenuItem();
        facturasMercadoPagoPendientesMnu = new javax.swing.JMenuItem();
        saldoFacturasCompraPendeintesMnu = new javax.swing.JMenuItem();
        facturasDeMercadoPagoMnu = new javax.swing.JMenuItem();
        facturasMercadoPagoCompletadasMnu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        versionMnu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FACTURACION AUTOMATICA");

        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        randomBtn.setText("Fc Automática");
        randomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBtnActionPerformed(evt);
            }
        });

        notaCreditoBtn.setText("Nota de Crédito");
        notaCreditoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaCreditoBtnActionPerformed(evt);
            }
        });

        facturaMercadoPagoBtn.setText("Facturar Mercado Pago");
        facturaMercadoPagoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaMercadoPagoBtnActionPerformed(evt);
            }
        });

        facturaAutomPorImporteBtn.setText("Fc Autom.X Importe");

        jMenu1.setText("Abm");

        configuracionMnu.setText("Configuración");
        configuracionMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionMnuActionPerformed(evt);
            }
        });
        jMenu1.add(configuracionMnu);

        productosMnu.setText("Productos");
        productosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(productosMnu);

        verInactivosMnu.setText("Productos Inactivos");
        verInactivosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInactivosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(verInactivosMnu);

        productosUtilizadosMnu.setText("Productos utilizados");
        productosUtilizadosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosUtilizadosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(productosUtilizadosMnu);

        productosTopInactivosMnu.setText("Productos Utilizados Eliminados");
        productosTopInactivosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosTopInactivosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(productosTopInactivosMnu);

        rubrosMnu.setText("Rubros");
        rubrosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubrosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(rubrosMnu);

        subRubrosMnu.setText("Sub Rubros");
        subRubrosMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subRubrosMnuActionPerformed(evt);
            }
        });
        jMenu1.add(subRubrosMnu);

        clientesMnu.setText("Clientes");
        clientesMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMnuActionPerformed(evt);
            }
        });
        jMenu1.add(clientesMnu);

        tipoDocMnu.setText("Tipo Documento");
        tipoDocMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDocMnuActionPerformed(evt);
            }
        });
        jMenu1.add(tipoDocMnu);

        stockMnu.setText("Stock");
        stockMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMnuActionPerformed(evt);
            }
        });
        jMenu1.add(stockMnu);

        comprasPorImporteMnu.setText("COMPRAS POR IMPORTE");
        comprasPorImporteMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasPorImporteMnuActionPerformed(evt);
            }
        });
        jMenu1.add(comprasPorImporteMnu);

        articulosPorMontoMnu.setText("ARTÍCULOS POR MONTO");
        articulosPorMontoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articulosPorMontoMnuActionPerformed(evt);
            }
        });
        jMenu1.add(articulosPorMontoMnu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Verificar");

        verificarAfipMnu.setText("Estado Afip");
        verificarAfipMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarAfipMnuActionPerformed(evt);
            }
        });
        jMenu2.add(verificarAfipMnu);

        recuperarAfipMnu.setText("Recuperar de Afip");
        recuperarAfipMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarAfipMnuActionPerformed(evt);
            }
        });
        jMenu2.add(recuperarAfipMnu);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Herramientas");

        backupMnu.setText("Backup");
        backupMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupMnuActionPerformed(evt);
            }
        });
        jMenu5.add(backupMnu);

        duplicadoPdfMnu.setText("Duplicado Fc en Pdf");
        duplicadoPdfMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicadoPdfMnuActionPerformed(evt);
            }
        });
        jMenu5.add(duplicadoPdfMnu);

        importarMnu.setText("IMPORTAR");
        importarMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarMnuActionPerformed(evt);
            }
        });
        jMenu5.add(importarMnu);

        importarMercadoPagoMnu.setText("IMPORTAR MP");
        importarMercadoPagoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarMercadoPagoMnuActionPerformed(evt);
            }
        });
        jMenu5.add(importarMercadoPagoMnu);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Informes");

        ventasPorPeriodoMnu.setText("Ventas X Período");
        ventasPorPeriodoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasPorPeriodoMnuActionPerformed(evt);
            }
        });
        jMenu4.add(ventasPorPeriodoMnu);

        informeStockMnu.setText("Stock Actual");
        informeStockMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeStockMnuActionPerformed(evt);
            }
        });
        jMenu4.add(informeStockMnu);

        stockPeriodoProductoVentaMnu.setText("Stock x Período x Producto x Venta");
        stockPeriodoProductoVentaMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockPeriodoProductoVentaMnuActionPerformed(evt);
            }
        });
        jMenu4.add(stockPeriodoProductoVentaMnu);

        stockPeriodoProductoCompraMnu.setText("Stock x Período x Producto x Compra");
        stockPeriodoProductoCompraMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockPeriodoProductoCompraMnuActionPerformed(evt);
            }
        });
        jMenu4.add(stockPeriodoProductoCompraMnu);

        facturasMercadoPagoPendientesMnu.setText("FACTURAS MERCADO PAGO PENDIENTES");
        facturasMercadoPagoPendientesMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasMercadoPagoPendientesMnuActionPerformed(evt);
            }
        });
        jMenu4.add(facturasMercadoPagoPendientesMnu);

        saldoFacturasCompraPendeintesMnu.setText("SALDO DE FACTURAS COMPRA PENDIENTES");
        saldoFacturasCompraPendeintesMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoFacturasCompraPendeintesMnuActionPerformed(evt);
            }
        });
        jMenu4.add(saldoFacturasCompraPendeintesMnu);

        facturasDeMercadoPagoMnu.setText("FACTURAS CORRESPONDIENTES A MERCADO PAGO");
        facturasDeMercadoPagoMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasDeMercadoPagoMnuActionPerformed(evt);
            }
        });
        jMenu4.add(facturasDeMercadoPagoMnu);

        facturasMercadoPagoCompletadasMnu.setText("FACTURAS MERCADO PAGO COMPLETADAS");
        facturasMercadoPagoCompletadasMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasMercadoPagoCompletadasMnuActionPerformed(evt);
            }
        });
        jMenu4.add(facturasMercadoPagoCompletadasMnu);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("?");

        versionMnu.setText("Versión");
        versionMnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionMnuActionPerformed(evt);
            }
        });
        jMenu3.add(versionMnu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(facturaMercadoPagoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(facturaAutomPorImporteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(salirBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notaCreditoBtn)
                            .addComponent(randomBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(randomBtn)
                .addGap(18, 18, 18)
                .addComponent(notaCreditoBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirBtn)
                    .addComponent(facturaMercadoPagoBtn)
                    .addComponent(facturaAutomPorImporteBtn))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBtnActionPerformed
        facturar();
    }//GEN-LAST:event_randomBtnActionPerformed

    private void productosUtilizadosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosUtilizadosMnuActionPerformed
        productosUtilizados();

    }//GEN-LAST:event_productosUtilizadosMnuActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Desea Salir del programa?", "Atención", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            salir();
        }
    }//GEN-LAST:event_salirBtnActionPerformed

    private void configuracionMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionMnuActionPerformed
        configuracion();
    }//GEN-LAST:event_configuracionMnuActionPerformed

    private void verInactivosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInactivosMnuActionPerformed
        verProductosInactivos();
    }//GEN-LAST:event_verInactivosMnuActionPerformed

    private void verificarAfipMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarAfipMnuActionPerformed
        verificarAfip();
    }//GEN-LAST:event_verificarAfipMnuActionPerformed

    private void versionMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versionMnuActionPerformed
        versionFrm();
    }//GEN-LAST:event_versionMnuActionPerformed

    private void productosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosMnuActionPerformed
        productos();
    }//GEN-LAST:event_productosMnuActionPerformed

    private void rubrosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubrosMnuActionPerformed
        rubros();
    }//GEN-LAST:event_rubrosMnuActionPerformed

    private void subRubrosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subRubrosMnuActionPerformed
        subRubros();
    }//GEN-LAST:event_subRubrosMnuActionPerformed

    private void clientesMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesMnuActionPerformed
        clientes();
    }//GEN-LAST:event_clientesMnuActionPerformed

    private void tipoDocMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDocMnuActionPerformed
        documento();
    }//GEN-LAST:event_tipoDocMnuActionPerformed

    private void ventasPorPeriodoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasPorPeriodoMnuActionPerformed
        informeVXP();
    }//GEN-LAST:event_ventasPorPeriodoMnuActionPerformed

    private void stockMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMnuActionPerformed
        abmStock();

    }//GEN-LAST:event_stockMnuActionPerformed

    private void informeStockMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeStockMnuActionPerformed
        informeStock();
    }//GEN-LAST:event_informeStockMnuActionPerformed

    private void duplicadoPdfMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicadoPdfMnuActionPerformed
//        duplicadoPdf();
    }//GEN-LAST:event_duplicadoPdfMnuActionPerformed

    private void backupMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupMnuActionPerformed
//        backup();
    }//GEN-LAST:event_backupMnuActionPerformed

    private void recuperarAfipMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarAfipMnuActionPerformed
        recuperar();
    }//GEN-LAST:event_recuperarAfipMnuActionPerformed

    private void productosTopInactivosMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosTopInactivosMnuActionPerformed
        verProductoTopInactivos();
    }//GEN-LAST:event_productosTopInactivosMnuActionPerformed

    private void stockPeriodoProductoVentaMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockPeriodoProductoVentaMnuActionPerformed
        stockPeriodoProductoVenta();
    }//GEN-LAST:event_stockPeriodoProductoVentaMnuActionPerformed

    private void stockPeriodoProductoCompraMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockPeriodoProductoCompraMnuActionPerformed
        stockPeriodoProductoCompra();
    }//GEN-LAST:event_stockPeriodoProductoCompraMnuActionPerformed

    private void notaCreditoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaCreditoBtnActionPerformed
        notaCredito();
    }//GEN-LAST:event_notaCreditoBtnActionPerformed

    private void importarMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarMnuActionPerformed
        importar();
    }//GEN-LAST:event_importarMnuActionPerformed

    private void importarMercadoPagoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarMercadoPagoMnuActionPerformed
        importarMercadoPago();
    }//GEN-LAST:event_importarMercadoPagoMnuActionPerformed

    private void facturaMercadoPagoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaMercadoPagoBtnActionPerformed
        facturaMercadoPago();
    }//GEN-LAST:event_facturaMercadoPagoBtnActionPerformed

    private void comprasPorImporteMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasPorImporteMnuActionPerformed
        comprasPorImporte();
    }//GEN-LAST:event_comprasPorImporteMnuActionPerformed

    private void saldoFacturasCompraPendeintesMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoFacturasCompraPendeintesMnuActionPerformed
        saldoPendienteFacturasCompra();
    }//GEN-LAST:event_saldoFacturasCompraPendeintesMnuActionPerformed

    private void facturasMercadoPagoPendientesMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasMercadoPagoPendientesMnuActionPerformed
        facturasMercadoPagoPendientes();
    }//GEN-LAST:event_facturasMercadoPagoPendientesMnuActionPerformed

    private void facturasDeMercadoPagoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasDeMercadoPagoMnuActionPerformed
        facturasDeMercadoPago();
    }//GEN-LAST:event_facturasDeMercadoPagoMnuActionPerformed

    private void facturasMercadoPagoCompletadasMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasMercadoPagoCompletadasMnuActionPerformed
        facturasMercadoPagoCompletadas();
    }//GEN-LAST:event_facturasMercadoPagoCompletadasMnuActionPerformed

    private void articulosPorMontoMnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articulosPorMontoMnuActionPerformed
        abmArticulosPorMonto();
    }//GEN-LAST:event_articulosPorMontoMnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem articulosPorMontoMnu;
    private javax.swing.JMenuItem backupMnu;
    private javax.swing.JMenuItem clientesMnu;
    private javax.swing.JMenuItem comprasPorImporteMnu;
    private javax.swing.JMenuItem configuracionMnu;
    private javax.swing.JMenuItem duplicadoPdfMnu;
    private javax.swing.JButton facturaAutomPorImporteBtn;
    private javax.swing.JButton facturaMercadoPagoBtn;
    private javax.swing.JMenuItem facturasDeMercadoPagoMnu;
    private javax.swing.JMenuItem facturasMercadoPagoCompletadasMnu;
    private javax.swing.JMenuItem facturasMercadoPagoPendientesMnu;
    private javax.swing.JMenuItem importarMercadoPagoMnu;
    private javax.swing.JMenuItem importarMnu;
    private javax.swing.JMenuItem informeStockMnu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton notaCreditoBtn;
    private javax.swing.JMenuItem productosMnu;
    private javax.swing.JMenuItem productosTopInactivosMnu;
    private javax.swing.JMenuItem productosUtilizadosMnu;
    private javax.swing.JButton randomBtn;
    private javax.swing.JMenuItem recuperarAfipMnu;
    private javax.swing.JMenuItem rubrosMnu;
    private javax.swing.JMenuItem saldoFacturasCompraPendeintesMnu;
    private javax.swing.JButton salirBtn;
    private javax.swing.JMenuItem stockMnu;
    private javax.swing.JMenuItem stockPeriodoProductoCompraMnu;
    private javax.swing.JMenuItem stockPeriodoProductoVentaMnu;
    private javax.swing.JMenuItem subRubrosMnu;
    private javax.swing.JMenuItem tipoDocMnu;
    private javax.swing.JMenuItem ventasPorPeriodoMnu;
    private javax.swing.JMenuItem verInactivosMnu;
    private javax.swing.JMenuItem verificarAfipMnu;
    private javax.swing.JMenuItem versionMnu;
    // End of variables declaration//GEN-END:variables

    private void salir() {
        System.exit(0);
    }

    private void configuracion() {
        ModificarConfiguracionTopFrame mctf = new ModificarConfiguracionTopFrame();
        mctf.setVisible(true);
        this.dispose();
    }

    private void facturar() {
        FacturarFrame ff = new FacturarFrame();
        ff.setVisible(true);
        this.dispose();
    }

    private void facturaWebUnica() {
        FacturaWebFrame fwf = new FacturaWebFrame();
        fwf.setVisible(true);
        this.dispose();
    }

    private void productos() {
        AbmProductoFrame apf = new AbmProductoFrame(null);
        apf.setVisible(true);
        this.dispose();
    }

    private void rubros() {
        AbmRubroFrame arf = new AbmRubroFrame();
        arf.setVisible(true);
        this.dispose();
    }

    private void subRubros() {
        AbmSubRubroFrame arf = new AbmSubRubroFrame();
        arf.setVisible(true);
        this.dispose();
    }

    private void clientes() {
        AbmClienteFrame acf = new AbmClienteFrame();
        acf.setVisible(true);
        this.dispose();
    }

    private void documento() {
        AbmTipoDocForm atdf = new AbmTipoDocForm();
        atdf.setVisible(true);
        this.dispose();
    }

    private void informeVXP() {
        InformeVentasPorPeriodoFrame ivppf = new InformeVentasPorPeriodoFrame(null, null, null);
        ivppf.setVisible(true);
        this.dispose();
    }

    private void recuperar() {
        RecuperarDeAfipFrame ivppf = new RecuperarDeAfipFrame();
        ivppf.setVisible(true);
        this.dispose();
    }

    private void informeStock() {
        InformeStockFrame isf = new InformeStockFrame();
        isf.setVisible(true);
        this.dispose();
    }

    private void duplicadoFc() {
        DuplicadoFacturaFrame dff = new DuplicadoFacturaFrame();
        dff.setVisible(true);
        this.dispose();
    }

    private void facturaPanificados() {
        FacturaWebPanificadosFrame fwpf = new FacturaWebPanificadosFrame();
        fwpf.setVisible(true);
        this.dispose();
    }

//    private void facturarPanificados() {
//        FacturarPanificadosFrame ff = new FacturarPanificadosFrame();
//        ff.setVisible(true);
//        this.dispose();
//    }

//    private void duplicadoPdf() {
//        DuplicadoFacturaPdfFrame dff = new DuplicadoFacturaPdfFrame();
//        dff.setVisible(true);
//        this.dispose();
//    }

//    private void borrarTemporales() {
//        int a = JOptionPane.showConfirmDialog(this, "CONFIRME ELIMINAR TEMPORALES", "Atención", JOptionPane.YES_NO_OPTION);
//        if (a == 0) {
//            List<RenglonFc> renglones = null;
//            try {
//                renglones = new RenglonFcService().getAllrenglones();
//            } catch (Exception ex) {
//                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            if (renglones != null && !renglones.isEmpty()) {
//                for (RenglonFc r : renglones) {
//                    try {
//                        new RenglonFcService().deleteRenglon(r);
//                    } catch (Exception ex) {
//                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//            List<Factura> facturas = null;
//            try {
//                facturas = new FcService().getAllFacturas();
//            } catch (Exception ex) {
//                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            if (facturas != null && !facturas.isEmpty()) {
//                for (Factura fc : facturas) {
//                    try {
//                        new FcService().deleteFactura(fc);
//                    } catch (Exception ex) {
//                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//            JOptionPane.showMessageDialog(this, "PROCESO TERMINADO");
//        }
//    }
    private void backup() {
        BackupFrame bf = new BackupFrame();
        bf.setVisible(true);
        this.dispose();
    }

    private void verProductoTopInactivos() {
        AbmProductosTopInactivosFrame apt = new AbmProductosTopInactivosFrame();
        apt.setVisible(true);
        this.dispose();
    }

    private void verProductosInactivos() {
        AbmProductosInactivosFrame aptif = new AbmProductosInactivosFrame(null);
        aptif.setVisible(true);
        this.dispose();
    }

    private void stockPeriodoProductoVenta() {
        StockPeriodoProductoFrame sppf = new StockPeriodoProductoFrame();
        sppf.setVisible(true);
        this.dispose();
    }

    private void stockPeriodoProductoCompra() {
        StockPeriodoProductoCompraFrame sppcf = new StockPeriodoProductoCompraFrame();
        sppcf.setVisible(true);
        this.dispose();
    }

    private void notaCredito() {
        NotaCreditoFrame ncf = new NotaCreditoFrame();
        ncf.setVisible(true);
        this.dispose();
    }

    private void productosUtilizados() {
        AbmProductosTopFrame apt = new AbmProductosTopFrame();
        apt.setVisible(true);
        this.dispose();
    }

    private void verificarAfip() {
        VerificarAfipFrame vaf = new VerificarAfipFrame();
        vaf.setVisible(true);
        this.dispose();
    }

    private void abmStock() {
        AbmStockFrame asf = new AbmStockFrame();
        asf.setVisible(true);
        this.dispose();
    }

    private void versionFrm() {
        VersionFrame vf = new VersionFrame();
        vf.setVisible(true);
        this.dispose();
    }

    private void importar() {
        JFileChooser selector = new JFileChooser();
        selector.showOpenDialog(this);
        File archivo = selector.getSelectedFile();
        if (archivo != null) {
            ImportarProductoFrame ipf = new ImportarProductoFrame(archivo);
            ipf.setVisible(true);
            this.dispose();
        }
    }

    private void importarMercadoPago() {
        JFileChooser selector = new JFileChooser();
        selector.showOpenDialog(this);
        File archivo = selector.getSelectedFile();
        if (archivo != null) {
            ImportarClientesMercadoPagoFrame ipf = new ImportarClientesMercadoPagoFrame(archivo);
            ipf.setVisible(true);
            this.dispose();
        }
    }

    private void facturaMercadoPago() {
        FacturarMercadoPagoFrame fmpf = new FacturarMercadoPagoFrame();
        fmpf.setVisible(true);
        this.dispose();
    }

    private void comprasPorImporte() {
        AbmFacturasComprasFrame afcf = new AbmFacturasComprasFrame();
        afcf.setVisible(true);
        this.dispose();
    }

    private void saldoPendienteFacturasCompra() {
        ArticulosConSaldoPendienteParaAsignarFrame fccsppaf = new ArticulosConSaldoPendienteParaAsignarFrame();
        fccsppaf.setVisible(true);
        this.dispose();
    }

    private void facturasMercadoPagoPendientes() {
        FacturasMercadoPagoPendientesFacturarFrame fmppff = new FacturasMercadoPagoPendientesFacturarFrame();
        fmppff.setVisible(true);
        this.dispose();
    }

    private void facturasDeMercadoPago() {
        FacturasDeMercadoPagoFrame fdmpf = new FacturasDeMercadoPagoFrame();
        fdmpf.setVisible(true);
        this.dispose();
    }

    private void facturasMercadoPagoCompletadas() {
        FacturasMercadoPagoCompletadasFacturarFrame fmppff = new FacturasMercadoPagoCompletadasFacturarFrame();
        fmppff.setVisible(true);
        this.dispose();
    }

    private void abmArticulosPorMonto() {
        AbmArticulosPorMontoFrame aapmf = new AbmArticulosPorMontoFrame();
        aapmf.setVisible(true);
        this.dispose();
    }
}
