package com.ventas.frame;

import com.ventas.entities.Cliente;
import com.ventas.entities.CompraClienteMercadoPago;
import com.ventas.entities.Configuracion;
import com.ventas.entities.ConfiguracionTop;
import com.ventas.entities.Factura;
import com.ventas.entities.FacturaCompraReferenciaMercadoPago;
import com.ventas.entities.FacturaIvaIntercambio;
import com.ventas.entities.IvaVentas;
import com.ventas.entities.Producto;
import com.ventas.entities.ProductoTop;
import com.ventas.entities.RenglonFactura;
import com.ventas.entities.RenglonFc;
import com.ventas.entities.Rubro;
import com.ventas.main.MainFrame;
import com.ventas.services.ClienteService;
import com.ventas.services.CompraClienteMercadoPagoService;
import com.ventas.services.ConfiguracionService;
import com.ventas.services.ConfiguracionTopService;
import com.ventas.services.FacturaCompraReferenciaMercadoPagoService;
import com.ventas.services.FcService;
import com.ventas.services.IvaVentasService;
import com.ventas.services.ProductoService;
import com.ventas.services.ProductoTopService;
import com.ventas.services.RenglonFacturaService;
import com.ventas.services.RenglonFcService;
import com.ventas.services.RubroService;
import com.ventas.util.Constantes;
import com.ventas.util.UtilFrame;
import com.ventas.util.UtilAfip;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.Thread.sleep;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JProgressBar;

/**
 *
 * @author argia
 */
public class FacturarMercadoPago2Frame1 extends javax.swing.JFrame {

    private DecimalFormat df = new DecimalFormat("#0.00");
//    private DecimalFormat df3 = new DecimalFormat("#0.000");
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private List<CompraClienteMercadoPago> comprasMp = null;
    private List<Rubro> rubros;
    private String origen;
    private Double minimoMp;
//    private List<RenglonFc> renglones = null;
    private List<Factura> facturas;
    private List<ProductoTop> productos;
    private Date fechaFacturas;
//    private String ultinu;
//    private String ultimpor;
    private ConfiguracionTop cf;
    private int maxNro;

    /**
     * Creates new form FacturasMercadoPagoFrame
     *
     * @param origen
     */
    public FacturarMercadoPago2Frame1(String origen) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 100, 255));
        this.setLocationRelativeTo(null);
        this.origen = origen;
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ultimaFechaTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        procesarBtn = new javax.swing.JButton();
        presentarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        segDeTxt = new javax.swing.JTextField();
        segAlTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        barral = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        ultimoNumeroTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ultimoImporteTxt = new javax.swing.JTextField();
        sacarBtn = new javax.swing.JButton();
        verCpbteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FACTURACION MERCADO PAGO");

        jLabel1.setText("FECHA FACTURAS:");

        jLabel2.setText("ULTIMA FECHA SISTEMA:");

        ultimaFechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ultimaFechaTxt.setText("ULT.FECHA");

        fechaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaTxt.setText("FECHA");
        fechaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaTxtKeyPressed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "CUIT", "NOMBRE", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(300);
            tabla.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        procesarBtn.setText("CALCULAR FC");
        procesarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarBtnActionPerformed(evt);
            }
        });
        procesarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                procesarBtnKeyPressed(evt);
            }
        });

        presentarBtn.setText("PRESENTAR");
        presentarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("SEGUNDOS ENTRE FC:");

        segDeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        segDeTxt.setText("SEG");

        segAlTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        segAlTxt.setText("SEG");

        jLabel3.setText("TABACALERA:");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });

        jLabel5.setText("Ult.Fc:");

        ultimoNumeroTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ultimoNumeroTxt.setText("U.NUM.FC");

        jLabel6.setText("Ult.IMPORTE:");

        ultimoImporteTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ultimoImporteTxt.setText("U.IMPORTE");

        sacarBtn.setText("SACAR");
        sacarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarBtnActionPerformed(evt);
            }
        });

        verCpbteBtn.setText("VER cpte");
        verCpbteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCpbteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ultimaFechaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(fechaTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ultimoNumeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ultimoImporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(verCpbteBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(procesarBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presentarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(sacarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(segDeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(segAlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ultimaFechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procesarBtn)
                    .addComponent(jLabel5)
                    .addComponent(ultimoNumeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ultimoImporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verCpbteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presentarBtn)
                    .addComponent(sacarBtn)
                    .addComponent(jLabel4)
                    .addComponent(segDeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segAlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaTxtKeyPressed
        if (evt.getKeyCode() == 10) {

            String fe = fechaTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                try {
                    fechaFacturas = sdf.parse(fe);
                    if (verificarFecha(fechaFacturas)) {
                        combo.addFocusListener(null);
                        combo.showPopup();
                        combo.requestFocus();
                    }
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
                    fechaTxt.requestFocus();
                    return;
                }

            } else {
                if (largo > 10) {
                    JOptionPane.showMessageDialog(this, "ERROR EN LARGO DE FECHA");
                    return;
                }
            }
            fe = UtilFrame.fecha(fe);
            fechaTxt.setText(fe);
        }
    }//GEN-LAST:event_fechaTxtKeyPressed

    private void procesarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarBtnActionPerformed
        procesar();
    }//GEN-LAST:event_procesarBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver(origen);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void presentarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentarBtnActionPerformed
        int row = combo.getSelectedIndex();
        if (row > 0) {
            presentar();
        }
    }//GEN-LAST:event_presentarBtnActionPerformed

    private void procesarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_procesarBtnKeyPressed
        if (evt.getKeyCode() == 10) {
            procesar();
        }
    }//GEN-LAST:event_procesarBtnKeyPressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        if (evt.getModifiers() == 16) {
            int row = combo.getSelectedIndex();
            if (row > 0) {
                procesarBtn.requestFocus();
            }
        }
    }//GEN-LAST:event_comboActionPerformed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        if (evt.getKeyCode() == 10) {
            int row = combo.getSelectedIndex();
            if (row > 0) {
                procesarBtn.requestFocus();
            }
        }
    }//GEN-LAST:event_comboKeyPressed

    private void sacarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarBtnActionPerformed
        int cantidadSeleccionada = tabla.getSelectedRowCount();
        int a[] = tabla.getSelectedRows();
        if (cantidadSeleccionada < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN PRODUCTO PARA SACER");
            return;
        }
        for (int n = cantidadSeleccionada - 1; n > -1; n--) {
            if (a[n] < facturas.size()) {
                facturas.remove(a[n]);
            }
        }
        llenarTabla2();
    }//GEN-LAST:event_sacarBtnActionPerformed

    private void verCpbteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCpbteBtnActionPerformed
        int row = tabla.getSelectedRow();
        Factura f = facturas.get(row);

    }//GEN-LAST:event_verCpbteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturarMercadoPago2Frame1(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barral;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton presentarBtn;
    private javax.swing.JButton procesarBtn;
    private javax.swing.JButton sacarBtn;
    private javax.swing.JTextField segAlTxt;
    private javax.swing.JTextField segDeTxt;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField ultimaFechaTxt;
    private javax.swing.JTextField ultimoImporteTxt;
    private javax.swing.JTextField ultimoNumeroTxt;
    private javax.swing.JButton verCpbteBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        presentarBtn.setEnabled(false);
        verCpbteBtn.setVisible(false);
        String ultimaFecha = UtilFrame.ultimaFecha("20300377425");
        if (ultimaFecha != null) {
            ultimaFechaTxt.setText(ultimaFecha);
        } else {
            ultimaFechaTxt.setText("01-01-2020");
        }
        fechaTxt.setText("");
        fechaTxt.requestFocus();
        segDeTxt.setText("1");
        segAlTxt.setText("3");
        combo.removeAllItems();
        combo.addItem("");
        rubros = null;
        try {
            rubros = new RubroService().getAllRubros();
        } catch (Exception ex) {
            Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Rubro r : rubros) {
            combo.addItem(r.getNombre());
        }
        Integer ult_num = 0;
        String ult_impFc;
        try {
            ult_num = new IvaVentasService().getUltimoNumeroFactura("20300377425");
            ult_impFc = new IvaVentasService().getUltimoImporteFactura("20300377425");
        } catch (Exception ex) {
            return;
        }
        ultimoNumeroTxt.setText(ult_num.toString());
        ultimoImporteTxt.setText(ult_impFc);
        if (origen.equals("V")) {
            llenarCampos();
        }
    }

    private void volver(String o) {
        if (o.equals("M")) {
            MainFrame mf = new MainFrame();
            mf.setVisible(true);
        } else {
            Integer row = tabla.getSelectedRow();
            Factura f = facturas.get(row);
            VerFacturaFrame mf = new VerFacturaFrame(f);
            mf.setVisible(true);
        }
        this.dispose();
    }

    private void calcular() {
        UtilFrame.limpiarTabla(tabla);
        calcularFacturas();
        llenarTabla();
        presentarBtn.setEnabled(true);
    }

    private void llenarTabla2() {
        UtilFrame.limpiarTabla(tabla);
        if (facturas != null && !facturas.isEmpty()) {
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            Double sumaDeFacturas = 0.0;
            int row = 1;
            for (Factura fa : facturas) {
                Object o[] = new Object[4];
                o[0] = row;
                row += 1;
                o[1] = fa.getCliente().getCuit();
                o[2] = fa.getCliente().getRazonSocial();
                o[3] = df.format(fa.getTotal());
                sumaDeFacturas += fa.getTotal();
                tbl.addRow(o);
            }
            Object o[] = new Object[4];
            o[0] = "";
            o[2] = "TOTAL A PROCESAR";
            o[3] = df.format(sumaDeFacturas);
            tbl.addRow(o);
            tabla.setModel(tbl);
        }
    }

    private void llenarTabla() {

        facturas = null;
        try {
            facturas = new FcService().getAllFacturasActivas();
        } catch (Exception ex) {
            Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        llenarTabla2();
    }

    private void presentar() {
        if (fechaTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
            return;
        }
        try {
            fechaFacturas = sdf.parse(fechaTxt.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "ERROR EN FECHA");
            return;
        }
        int a = JOptionPane.showConfirmDialog(this, "VERIFICO LA FECHA DE LAS FACTURAS???", "Atención",
                JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            int row = combo.getSelectedIndex();
            if (row < 1) {
                JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR RUBRO");
                return;
            }
            if (facturas != null && !facturas.isEmpty()) {
//                try {
//                    Integer ultimoNro = new IvaVentasService().getUltimoNumeroFactura();
//                } catch (Exception ex) {
//                    Logger.getLogger(FacturarMercadoPago2Frame.class.getName()).log(Level.SEVERE, null, ex);
//                }
//                for (Factura fa : facturas) {
                int tim1 = Integer.valueOf(segDeTxt.getText().trim());
                int tim2 = Integer.valueOf(segAlTxt.getText().trim());
                try {
                    FileWriter fichero = new FileWriter("D:/ventasJo/temp.txt");
                    PrintWriter pw = new PrintWriter(fichero);
                    pw.println(sdf.format(fechaFacturas));
                    pw.println(tim1);
                    pw.println(tim2);

                    pw.close();
                } catch (Exception e) {
//                    e.printStackTrace();
                }
                presentarBtn.setEnabled(false);
                sacarBtn.setEnabled(false);
                procesarBtn.setEnabled(false);
                combo.setEnabled(false);
                fechaTxt.setEditable(false);
                barral();
//                }
            } else {
                JOptionPane.showMessageDialog(this, "NO HAY FACTURAS CARGADAS DISPONIBLES PARA CALCULAR LOS IMPUESTO");
            }
        }
    }

    private Boolean verificarFecha(Date fecha) {
        Date hoy = new Date();
        if (fecha.after(hoy)) {
            JOptionPane.showMessageDialog(this, "NO PUEDE FACTURAR CON FECHA POSTERIOR A HOY");
            fechaTxt.requestFocus();
            return false;
        }
        try {
            Date ultimaFecha = sdf.parse(ultimaFechaTxt.getText());
            if (fecha.before(ultimaFecha)) {
                JOptionPane.showMessageDialog(this, "NO PUEDE FACTURAR CON FECHA ANTERIOR A ULTIMA");
                fechaTxt.requestFocus();
                return false;
            }
            Date f5d = new Date();
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(f5d);
            calendar.add(Calendar.DATE, -6);
            f5d = calendar.getTime();
            if (fecha.before(f5d)) {
                JOptionPane.showMessageDialog(this, "NO DEBE SUPERAR 5 DIAS ATRAS");
                return false;
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "ERROR EN FECHAS");
            fechaTxt.requestFocus();
            return false;
        }
        return true;
    }

    private void barral() {
        Avanzando_3 avanzando = new Avanzando_3();
//        presentarBtn.setEnabled(false);
//        procesarBtn.setEnabled(false);
//        sacarBtn.setEnabled(false);
        avanzando.setBar(barral);
        Thread hilo = new Thread(avanzando);
        hilo.start();
    }

    private void copiarStock() {
        productos = null;
        try {
            productos = new ProductoTopService().getAllProductoTopActivos();
        } catch (Exception ex) {
            Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (productos != null && !productos.isEmpty()) {
            int orden = 0;
            for (ProductoTop p : productos) {
                Integer cod_pro = p.getCodigo();
                Producto pro;
                try {
                    pro = new ProductoService().getProductoByCodigo(cod_pro);
                } catch (Exception ex) {
                    continue;
                }
                Float cant_pro = pro.getStock();
                p.setStock(cant_pro);
                p.setDetalle(pro.getDetalle());
                p.setPrecio(pro.getPrecio());
                p.setImpuesto(pro.getImpuesto());
                p.setUsado(false);
                p.setOrden(orden);
                orden += 1;
                try {
                    new ProductoTopService().updateProductoTop(p);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,
                            "ERROR ACTUALIZANDO PRODUCTO SELECCIONADO" + p.getDetalle());
                    return;
                }
            }
        }
//        System.exit(0);
    }

    private void calcularFacturas() {
        comprasMp = null;
        try {
            comprasMp = new CompraClienteMercadoPagoService().getAllFacturasPendientesDeProcesar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR LEYENDO COMPRAS DE MERCADO PAGO PENDIENTES");
            return;
        }
        if (comprasMp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NO HAY COMPRAS DE MP REGISTRADAS");
            return;
        }
        Producto prod_logistica;
        try {
            prod_logistica = new ProductoService().getProductoLogistica();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR LEYENDO PRODUCTO LOGISTICA");
            return;
        }
        Boolean hayProductos = false;
        for (ProductoTop pr0 : productos) {
            if (pr0.getStock() > 0) {
                hayProductos = true;
                break;
            }
        }
        if (!hayProductos) {
            JOptionPane.showMessageDialog(this, "NO HAY STOCK DE PRODUCTOS");
            return;
        }
        for (CompraClienteMercadoPago ccmp : comprasMp) {
            // aqui se agrega la modificacion
            Double limite = ccmp.getImporte();
            productos = null;
            try {
                productos = new ProductoTopService().getAllProductoTopActivosConLimite(limite);
            } catch (Exception ex) {
                Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(Level.SEVERE, null, ex);
            }
            List<ProductoTop> productos2=null;
            try {
                productos2 = new ProductoTopService().getAllProductoTopActivos();
            } catch (Exception ex) {
                Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(Level.SEVERE, null, ex);
            }
            // aquí termina
            Double acumuladoFactura = 0.0;
            Float porcentualIvaFc = 21F;
//            Float cant;
            Integer nro = 0;
            Cliente cliente;
            String cuit = ccmp.getCuit();
            try {
                cliente = new ClienteService().getClienteByCuit(cuit);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR EN CUIT CLIENTE");
                return;
            }
            Double totalFactura = ccmp.getImporte();
            Double saldoFactura;
            Producto pro;
            Factura factura = new Factura();
            List<RenglonFc> renglones = new ArrayList<>();
            Double totalGravado = 0.0;
            Double totalImpuesto = 0.0;
            Double totalIva = 0.0;
            Boolean salga = false;
            Boolean usados = true;
            do {
                // generar producto y cantidad
                ProductoTop pt = generarProducto();
                if (pt == null) {
                    JOptionPane.showMessageDialog(this, "SIN PRODUCTOS");
                    salga = true;
                }
                if (pt.getCantidadMinimaVenta() == null) {
                    JOptionPane.showMessageDialog(this,
                            "PRODUCTO SIN MINIMO ESTABLECIDO " + pt.getDetalle());
                    return;
                }
                if (pt.getCantidadMaximaVenta() == null) {
                    JOptionPane.showMessageDialog(this,
                            "PRODUCTO SIN MAXIMO ESTABLECIDO " + pt.getDetalle());
                    return;
                }
                Integer min = pt.getCantidadMinimaVenta();
                Integer max = pt.getCantidadMaximaVenta();
                Integer frac = pt.getFraccion();
                Float cant = generarCantidad(min, max, frac).floatValue();

                if (cant > pt.getStock()) {
                    cant = pt.getStock();
                }

                Integer codigo = pt.getCodigo();
                try {
                    pro = new ProductoService().getProductoByCodigo(codigo);
                } catch (Exception ex) {
                    continue;
                }
                nro += 1;
                Float porcentualIva = pro.getAlicuotaIva().getAlicuota();
                Double neto = pt.getPrecio() * cant;
                Double precio = neto * (1 + porcentualIva / 100);
                Float impuesto = pt.getImpuesto() * cant;
                Double totalLinea = precio + impuesto;
                acumuladoFactura += totalLinea;
                saldoFactura = totalFactura - acumuladoFactura;
                System.out.println(nro);
//                System.out.println(cant);
//                System.out.println(neto);
//                System.out.println(porcentualIva);
//                System.out.println(precio);
//                System.out.println(impuesto);
//                System.out.println(totalLinea);
//                System.out.println(acumuladoFactura);
//                System.out.println(saldoFactura);
//                System.out.println(totalFactura);
//                JOptionPane.showMessageDialog(this, "VER");
                if (saldoFactura < 0) {
                    acumuladoFactura -= totalLinea;
                    saldoFactura = totalFactura - acumuladoFactura;
                    totalLinea = saldoFactura;
                    totalGravado -= neto;
                    totalImpuesto -= impuesto;
                    System.out.println(saldoFactura);
                    System.out.println(minimoMp);
//                    JOptionPane.showMessageDialog(this, "VER");
                    if (saldoFactura < minimoMp) {
                        cant = 1F;
                        impuesto = 0F;
                        neto = totalLinea / (1 + porcentualIva / 100);
                        precio = totalLinea;
                        pro = prod_logistica;
                        totalFactura = ccmp.getImporte();
                        totalGravado += neto;
                        totalImpuesto += impuesto;
                        acumuladoFactura += totalLinea;
//                        saldoFactura = totalFactura - acumuladoFactura;

                        //         totalImpuesto += impuesto;
                        salga = true;
                    } else {
                        nro -= 1;
                        continue;
                    }
                }
                RenglonFc rfc = new RenglonFc();
                rfc.setAnulado(false);
                rfc.setCantidad(cant);
                rfc.setCostoG(0.0);
                rfc.setCostoI(0.0);
                rfc.setDescuento(0.0);
                rfc.setExento(0.0);
                rfc.setFabricacion(false);
                rfc.setFactura(factura);
                rfc.setGravado(neto);
                totalGravado += neto;
                totalImpuesto += impuesto;
                rfc.setGravado0(0.0);
                rfc.setGravado10_5(0.0);
                rfc.setGravado27(0.0);
                rfc.setImpuesto(impuesto.doubleValue());
                rfc.setItemNro(nro);
                Double iva = precio - neto;
                rfc.setIva(iva);
                totalIva += iva;
                rfc.setIva0(0.0);
                rfc.setIva10_5(0.0);
                rfc.setIva27(0.0);
                rfc.setNoGravado(0.0);
                rfc.setProducto(pro);
                rfc.setSugerido(0.0);
                rfc.setTotal(totalLinea);

                renglones.add(rfc);
//                System.out.println(nro);
//                System.out.println(cant);
//                System.out.println(neto);
//                System.out.println(porcentualIva);
//                System.out.println(precio);
//                System.out.println(impuesto);
//                System.out.println(totalLinea);
//                System.out.println(acumuladoFactura);
//                System.out.println(saldoFactura);
//                System.out.println(totalFactura);
//                JOptionPane.showMessageDialog(this, "VER");

                if (!pro.getEsLogistica()) {
                    pt.setStock(pt.getStock() - cant);
                    pt.setUsado(true);
                    try {
                        new ProductoTopService().updateProductoTop(pt);
                    } catch (Exception ex) {
                        Logger.getLogger(FacturarMercadoPago2Frame1.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "ERR 795");
                    }
                }
                usados = true;
                for (ProductoTop p1 : productos) {
                    if (!p1.getUsado()) {
                        usados = false;
                        break;
                    }
                }
                if (usados) {
                    salga = true;
                }
            } while (!salga);
            if (usados) {
                System.out.println("TODOS USADOS");
            }
            System.out.println("SALGO");
            totalImpuesto = 0.0;
            for (RenglonFc rf : renglones) {
                totalImpuesto += rf.getImpuesto();
            }
            totalFactura = ccmp.getImporte();
            String totalImpuestoStr = df.format(totalImpuesto);
            totalImpuesto = Double.valueOf(totalImpuestoStr.replace(",", "."));
            Double bruto = totalFactura - totalImpuesto;
            String brutoStr = df.format(bruto);
            bruto = Double.valueOf(brutoStr.replace(",", "."));
            totalGravado = bruto / (1 + porcentualIvaFc / 100);
            String totalGrvStr = df.format(totalGravado);
            totalGravado = Double.valueOf(totalGrvStr.replace(",", "."));
            totalIva = totalGravado * porcentualIvaFc / 100;
            String ivaStr = df.format(totalIva);
            totalIva = Double.valueOf(ivaStr.replace(",", "."));
            if (totalFactura > ccmp.getImporte() - 1) {
                factura.setAnulado(false);
                factura.setCliente(cliente);
                factura.setExento(0.0);
                factura.setFabricacion(false);
                factura.setFecha(fechaFacturas);
                factura.setGravado(totalGravado);
                factura.setGravado0(0.0);
                factura.setGravado10(0.0);
                factura.setGravado27(0.0);
                factura.setImpuesto(totalImpuesto);
                factura.setIva(totalIva);
                factura.setIva0(0.0);
                factura.setIva10(0.0);
                factura.setIva27(0.0);
                factura.setNoGravado(0.0);
                factura.setTotal(totalFactura);
                factura.setCompraClienteMercadoPago(ccmp);
//            facturas.add(factura);
                try {
                    new FcService().saveFactura(factura, renglones);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "ERROR GUARDANDO FACTURAS GENERADAS");
                    return;
                }
            } else {
                break;
            }
            for (ProductoTop pr_t : productos) {
                pr_t.setUsado(false);
                try {
                    new ProductoTopService().updateProductoTop(pr_t);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "ERROR 811");
                    return;
                }
            }
//            System.exit(0);
        }
    }

    private void cargarProductosTop() {
        productos = null;
        int row = combo.getSelectedIndex();
        if (row < 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN RUBRO");
            return;
        }
        Rubro ru = rubros.get(row - 1);
        try {
            productos = new ProductoTopService().getAllProductoTabacoTopActivos2(ru);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR NRO.851 - LEYENDO PRODUCTOS");
            return;
        }
        try {
            cf = new ConfiguracionTopService().getConfigTopById(1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR Nro.857 LEYENDO CONFIG TOP");
            return;
        }
        maxNro = cf.getOrderMaximo();
        minimoMp = cf.getImporteMinimoMercadoPago();
    }

    private ProductoTop generarProducto() {
        Boolean generado;
        ProductoTop productoT;
        do {
            generado = false;
            if (hayProductos()) {
                Random rnd = new Random();
                Double prod = rnd.nextDouble() * (maxNro + 1);
                int i = prod.intValue();
                int x = 0;
                if (!productos.isEmpty()) {
                    for (ProductoTop pptt : productos) {
                        if (pptt.getOrden().equals(i)) {
                            break;
                        }
                        x += 1;
                    }
                    try {
                        productoT = productos.get(x);
                        Float stock = productoT.getStock();
                        if (stock > 0) {
                            if (productoT.getUsado()) {
                                continue;
                            }
                            generado = true;
                        }
                    } catch (Exception ex) {
                        generado = false;
                        productoT = null;
                    }
                } else {
                    productoT = null;
                }
            } else {
                productoT = null;
            }
        } while (!generado);
        return productoT;
    }

    private Integer generarCantidad(Integer min, Integer max, Integer frac) {
        Boolean generado;
        int i;
        do {
            generado = false;
            Random rand = new Random();
            Double cnd = rand.nextDouble() * (max + 1);
            i = cnd.intValue();
            if (i % frac == 0) {
                if (i > min - 1) {
                    if (i < max + 1) {
                        generado = true;
                    }
                }
                if (i < 1) {
                    generado = false;
                }
            }
        } while (!generado);
        return i;
    }

    private void procesar() {
        copiarStock();

        List<Factura> facturasParaBorrar = null;
        try {
            facturasParaBorrar = new FcService().getAllFacturasActivas();
            for (Factura nf : facturasParaBorrar) {
                nf.setAnulado(true);
                new FcService().updateFactura(nf);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR ELIMINANDO FC ANTERIORES");
            return;
        }
        cargarProductosTop();
        if (productos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NO HAY PRODUCTOS PARA FACTURAR");
            return;
        }
        calcular();
    }

    private boolean hayProductos() {
        Boolean hay = false;
        if (productos != null && !productos.isEmpty()) {
            for (ProductoTop p : productos) {
                if (p.getStock() > 0) {
                    if (!p.getUsado()) {
                        hay = true;
                        break;
                    }
                }
            }
        }
        return hay;
    }

    private void llenarCampos() {
        presentarBtn.setEnabled(false);
        facturas = null;
        try {
            facturas = new FcService().getAllFacturasActivas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR nro. 1025");
            volver("V");
        }
        llenarTabla2();
    }
}

class Avanzando_3 implements Runnable {

    private JProgressBar bar;
    private Float incremento;
    private Float maximo;
    private final int tst = 0; // 1 esta en test

    @Override

    public void run() {
        this.getBar().setValue(1);
        String cuitTitular = Constantes.cuitTitular;
        String tipoDocTit = Constantes.tipoDocTit;
        String puntoVenta = Constantes.puntoVenta;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Float posF = 2F;
        Integer largo;
        // desde aqui
        Date fechaFacturas;
        Integer tim1;
        Integer tim2;
        String fechaString;
        String tim1String;
        String tim2String;
        File archivo = new File("D:/ventasJo/temp.txt");
        FileReader fr;
        try {
            fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);

            fechaString = br.readLine();
            tim1String = br.readLine();
            tim2String = br.readLine();
            br.close();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "ERROR 908");
            return;
        }
//        System.out.println(fechaString);
//        System.exit(0);
        try {
            fechaFacturas = sdf.parse(fechaString);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "ERROR 921");
            return;
        }
        tim1 = Integer.valueOf(tim1String);
        tim2 = Integer.valueOf(tim2String);

        List<Factura> nuevasFacturas = null;
        try {
            nuevasFacturas = new FcService().getAllFacturasActivas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR 931");
            return;
        }
        largo = nuevasFacturas.size();
        maximo = largo.floatValue();
        incremento = 100 / maximo;
        for (Factura ccmp : nuevasFacturas) {

            posF += incremento;
            Integer pos = posF.intValue();
            getBar().setValue(pos);

            CompraClienteMercadoPago compraMp = ccmp.getCompraClienteMercadoPago();
            String cuit_cliente = ccmp.getCompraClienteMercadoPago().getCuit();
            Cliente cliente;
            try {
                cliente = new ClienteService().getClienteByCuit(cuit_cliente);
                if (cliente == null) {
                    JOptionPane.showMessageDialog(null, "ERROR nro. 947 - LEYENDO CLIENTE");
                    return;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERROR nro. 947 - LEYENDO CLIENTE");
                return;
            }
            String pri = cuit_cliente.substring(0, 2);
            String med = cuit_cliente.substring(3, 11);
            String fin = cuit_cliente.substring(12, 13);
            String cuitCliente = pri + med + fin;
            String tipoDocCli = cliente.getTipo();
            int tim = 0;
            FacturaIvaIntercambio fii;
            do {
                Random rnd = new Random();
                Double segu = rnd.nextDouble() * (tim2 + 1);
                tim = segu.intValue();
            } while (tim < tim1 || tim > tim2);
            try {
                sleep(tim * 1000);
            } catch (InterruptedException ex) {
                JOptionPane.showMessageDialog(null, "ERR. con frecuencia de facturas");
                continue;
            }
            if (tst == 0) {
                fii = UtilAfip.presentarAfip(cuitTitular, tipoDocTit, cuitCliente,
                        tipoDocCli, ccmp.getGravado(), ccmp.getImpuesto(), ccmp.getIva(),
                        ccmp.getTotal(), fechaFacturas, puntoVenta);
            } else {
                fii = new FacturaIvaIntercambio();
                fii.setCae(123456789012345L);
                fii.setEstado("A");
                fii.setFecha(fechaFacturas);
                fii.setFechaVencimientoCae(fechaFacturas);
                fii.setLetra("B");
                Integer nroFc;
                try {
                    nroFc = new IvaVentasService().getUltimoNumeroFactura("20300377425");
                } catch (Exception ex) {
                    nroFc = 0;
                }
                fii.setNumero(nroFc + 1);
                fii.setSucursal(2);
            }
            List<RenglonFactura> listaRf = new ArrayList<>();
            List<RenglonFc> renglones;
            try {
                renglones = new RenglonFcService().getRenglonesByFc(ccmp);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "FC SIN RENGLONES");
                return;
            }
            if (fii != null) {
                Configuracion cfg = null;
                cfg.setNumeroFacturaB(fii.getNumero());
                IvaVentas iv = new IvaVentas();
                iv.setCae(fii.getCae());
                iv.setCliente(cliente);
                iv.setDescuentoGlobal(0.0);
                iv.setExento(0.0);
                iv.setFecha(fechaFacturas);
                iv.setFechaCae(fii.getFechaVencimientoCae());
                iv.setGravado(ccmp.getGravado());
                iv.setGravado0(0.0);
                iv.setGravado10_5(0.0);
                iv.setGravado27(0.0);
                iv.setImpuesto(ccmp.getImpuesto());
                iv.setIva(ccmp.getIva());
                iv.setIva0(0.0);
                iv.setIva10_5(0.0);
                iv.setIva27(0.0);
                iv.setLetra(fii.getLetra());
                iv.setLetraReferencia("x");
                iv.setNoGravado(0.0);
                iv.setNumeroFactura(fii.getNumero());
                iv.setNumeroFacturaReferencia(0);
                iv.setNumeroSucursal(fii.getSucursal());
                iv.setNumeroSucursalReferencia(0);
                iv.setTipoDoc(6);
                iv.setTotal(ccmp.getTotal());
                for (RenglonFc re : renglones) {
                    RenglonFactura rf = new RenglonFactura();

                    rf.setCantidad(re.getCantidad());
                    rf.setCostoG(0.0);
                    rf.setCostoI(0.0);
                    rf.setDescripcion(re.getProducto().getDetalle());
                    rf.setDescuento(0.0);
                    rf.setExento(0.0);
                    rf.setFabricacion(false);
                    rf.setGravado(re.getGravado());
                    rf.setGravado0(0.0);
                    rf.setGravado10_5(0.0);
                    rf.setGravado27(0.0);
                    rf.setImpuesto(re.getImpuesto());
                    rf.setItemNro(1);
                    rf.setIva(re.getIva());
                    rf.setIva0(0.0);
                    rf.setIva10_5(0.0);
                    rf.setIva27(0.0);
                    rf.setNoGravado(0.0);
                    rf.setProducto(re.getProducto());
                    rf.setSugerido(0.0);
                    rf.setTotal(re.getTotal());
                    rf.setIvaVentas(iv);
                    listaRf.add(rf);
                }

//                ArticuloCompra artCmpr = ccmp.getArticulo();
//                artCmpr.setGravado(artCmpr.getGravado() - iv.getGravado());
//                artCmpr.setImpuesto(artCmpr.getImpuesto() - iv.getImpuesto());
//                artCmpr.setIva(artCmpr.getIva() - iv.getIva());
//                artCmpr.setTotal(artCmpr.getTotal() - iv.getTotal());
                CompraClienteMercadoPago ccmpProceso = ccmp.getCompraClienteMercadoPago();
                ccmpProceso.setProcesado(true);
                FacturaCompraReferenciaMercadoPago fcrmp = new FacturaCompraReferenciaMercadoPago();
//                fcrmp.setArticuloCompra(artCmpr);
//                fcrmp.setCompraClienteMercadoPago(compraMp);
//                fcrmp.setIvaVentas(iv);
                try {
                    iv = new IvaVentasService().saveIvaVentas(iv);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERR nro 1076");
                }
                try {
                    for (RenglonFactura rn : listaRf) {
                        rn.setIvaVentas(iv);
                        new RenglonFacturaService().saveRenglon(rn);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERR nro. 1082");
                }
                try {
                    compraMp = new CompraClienteMercadoPagoService().updateCompraClientesImportados(compraMp);
//                    fcrmp.setCompraClienteMercadoPago(compraMp);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERR nro. 1088");
                }
                fcrmp.setCompraClienteMercadoPago(compraMp);
                fcrmp.setIvaVentas(iv);
                try {
                    new FacturaCompraReferenciaMercadoPagoService().saveFacturaCompraRmp(fcrmp);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERR nro. 1094");
                }
                try {
                    new ConfiguracionService().updateConfiguracion(cfg);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERR nro. 1322");
                }
//                try {
//                    new FacturaService().saveFacturaCompleta2(iv, listaRf,
//                            ccmpProceso, fcrmp);
//                } catch (Exception ex) {
//                    System.out.println(iv);
//                    System.out.println(listaRf);
//                    System.out.println(ccmpProceso);
//                    System.out.println(fcrmp);
//                    JOptionPane.showMessageDialog(null, "ERROR 1058");
//                    System.exit(0);
//                    break;
//                }
            } else {
                JOptionPane.showMessageDialog(null, "ERR AFIP NRO. 1239");
            }
        }

        JOptionPane.showMessageDialog(
                null, "         FINALIZADO         \n\nPUEDE SALIR DE ESTA PANTALLA");

    }

    public void setBar(JProgressBar bar) {
        this.bar = bar;
    }

    public JProgressBar getBar() {
        return bar;
    }

}
