/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventas.frame;

import com.ventas.entities.Cliente;
import com.ventas.entities.CompraClienteMercadoPago;
import com.ventas.entities.Domicilio;
import com.ventas.main.MainFrame;
import com.ventas.services.ClienteService;
import com.ventas.services.CompraClienteMercadoPagoService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author argia
 */
public class FacturarMercadoPagoInscriptosFrame extends javax.swing.JFrame {

    private List<CompraClienteMercadoPago> compras;

    /**
     * Creates new form FacturarMercadoPagoInscriptosFrame
     */
    public FacturarMercadoPagoInscriptosFrame() {
        initComponents();
        llenarFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        volverBtn = new javax.swing.JButton();
        facturarBtn = new javax.swing.JButton();
        agregarDomicilioBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "Fecha", "NOMB", "CUIT", "Calle", "Localid", "Prov", "CP", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        facturarBtn.setText("Facturar");
        facturarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarBtnActionPerformed(evt);
            }
        });

        agregarDomicilioBtn.setText("Agreg.Domicilio");
        agregarDomicilioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDomicilioBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        modificarBtn.setText("Modificar");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(facturarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(agregarDomicilioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(facturarBtn)
                    .addComponent(agregarDomicilioBtn)
                    .addComponent(eliminarBtn)
                    .addComponent(modificarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        modificar();
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        eliminar();
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void agregarDomicilioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDomicilioBtnActionPerformed
        agregarDomicilio();
    }//GEN-LAST:event_agregarDomicilioBtnActionPerformed

    private void facturarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarBtnActionPerformed
        facturar();
    }//GEN-LAST:event_facturarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPagoInscriptosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPagoInscriptosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPagoInscriptosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturarMercadoPagoInscriptosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturarMercadoPagoInscriptosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarDomicilioBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton facturarBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void llenarFrame() {
        compras = null;
        try {
            compras = new CompraClienteMercadoPagoService().getAllFacturasDeInscriptosPendientesDeProcesar();
        } catch (Exception ex) {
            Logger.getLogger(FacturarMercadoPagoInscriptosFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void modificar() {
        int row = tabla.getSelectedRow();
        int rows = tabla.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA COMPRA");
            return;
        }
        if (rows > 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR SOLO UNA COMPRA");
            return;
        }
        CompraClienteMercadoPago ccmp = compras.get(row);
        String cuit = ccmp.getCuit();
        Cliente cliente = null;
        try {
            cliente = new ClienteService().getClienteByCuit(cuit);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR LEYENDO CLIENTE");
            return;
        }
        if (cliente != null) {
            ModificarClienteFcAFrame mcfaf = new ModificarClienteFcAFrame(ccmp, cliente);
            mcfaf.setVisible(true);
            this.dispose();
        }
    }

    private void eliminar() {
        int row = tabla.getSelectedRow();
        int rows = tabla.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA COMPRA");
            return;
        }
        if (rows > 1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR SOLO UNA COMPRA");
            return;
        }
        CompraClienteMercadoPago ccmp = compras.get(row);
        int a = JOptionPane.showConfirmDialog(this, "CONFIRMA ELIMINAR MOVIMIENTO?",
                "Atención", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                new CompraClienteMercadoPagoService().deleteCompraClienteMP(ccmp);
                JOptionPane.showMessageDialog(this, "ELIMINADO");
                llenarFrame();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR ELIMINANDO MOVIMIENTO");
            }
        }
    }

    private void agregarDomicilio() {

    }

    private void facturar() {
        if (validar()) {

        }
    }

    private boolean validar() {
        Boolean valido = true;
        for (CompraClienteMercadoPago ccmp : compras) {
            String cuit = ccmp.getCuit();
            Cliente cliente = null;
            try {
                cliente = new ClienteService().getClienteByCuit(cuit);
            } catch (Exception ex) {
                
            }
            if (cliente.getDomicilio() != null) {
                Domicilio dm = cliente.getDomicilio();
            } else {
                valido = false;
                break;
            }

        }
        return valido;
    }
}
