/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventas.frame;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.Writer;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.itextpdf.text.DocumentException;
import com.ventas.entities.FacturaCompraReferenciaMercadoPago;
import com.ventas.entities.IvaVentas;
import com.ventas.entities.RenglonFactura;
import com.ventas.main.MainFrame;
import com.ventas.services.FacturaCompraReferenciaMercadoPagoService;
import com.ventas.services.RenglonFacturaService;
import com.ventas.util.Constantes;
import com.ventas.util.DesktopApi;
import com.ventas.util.PDFBuilder;
import com.ventas.util.UtilFrame;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author argia
 */
public class InformesImpresosFacturasMpFrame extends javax.swing.JFrame {

    private List<FacturaCompraReferenciaMercadoPago> facturas;
    private DecimalFormat df = new DecimalFormat("#0.00");
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private Date de = new Date();
    private Date al = new Date();
    private String fecha_qr;
    private static final SimpleDateFormat sdf_qr = new SimpleDateFormat("yyyy-MM-dd");
    private String numeroDoc_qr;
    private String puntoVenta_qr = "10";
    private String tipoComprobante_qr;
    private String numeroComprobante_qr;
    private final DecimalFormat df_matriz = new DecimalFormat("00000000");
    private String importe_qr;
    private String tipoDoc_qr;
    private String nroCae_qr;
    private final String ver_qr = "1";
    private final String cuit_qr = Constantes.cuitTitular;
    private final String cotiz_qr = "1";
    private final String moneda_qr = "PES";
    private final String tipoCodigoAutoriz_qr = "E";
    private final String url_qr = "https://www.afip.gob.ar/fe/qr/?p=";
    private static final int qrTamAncho = 200;
    private static final int qrTamAlto = 200;
    private static final String ruta = Constantes.ruta_qr;
    private static final String extension = ".png";
    private static final String formato = "png";

    /**
     * Creates new form InformesImpresosFacturasMpFrame
     */
    public InformesImpresosFacturasMpFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 100, 255));
        this.setExtendedState(6);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deTxt = new javax.swing.JTextField();
        volverBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        alTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pdfListadoBtn = new javax.swing.JButton();
        pdfFacturaBtn = new javax.swing.JButton();
        cuitTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INFORME IMPRESO FACTURAS MP");

        jLabel1.setText("DESDE:");

        deTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deTxt.setText("DE");
        deTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deTxtKeyPressed(evt);
            }
        });

        volverBtn.setText("VOLVER");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "F.COBRO", "CUIT", "NOMBRE", "IMPORTE", "VENDEDOR", "FACTURADO", "NRO.FC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel2.setText("HASTA:");

        alTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alTxt.setText("AL");
        alTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alTxtKeyPressed(evt);
            }
        });

        jLabel3.setText("CUIT:");

        pdfListadoBtn.setText("PDF LISTADO");
        pdfListadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfListadoBtnActionPerformed(evt);
            }
        });

        pdfFacturaBtn.setText("VER FC EN PDF");
        pdfFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfFacturaBtnActionPerformed(evt);
            }
        });

        cuitTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cuitTxt.setText("CUIT");
        cuitTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cuitTxtKeyPressed(evt);
            }
        });

        jLabel4.setText("<< COLOQUE GUIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pdfListadoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(pdfFacturaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 287, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(alTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cuitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBtn)
                    .addComponent(pdfListadoBtn)
                    .addComponent(pdfFacturaBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = deTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                try {
                    de = sdf.parse(deTxt.getText());
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "ERROR 252");
                    return;
                }
                alTxt.requestFocus();
            } else {
                if (largo > 10) {
                    JOptionPane.showMessageDialog(this, "ERROR EN LARGO DE FECHA");
                    return;
                }
            }
            fe = UtilFrame.fecha(fe);
            deTxt.setText(fe);
        }
    }//GEN-LAST:event_deTxtKeyPressed

    private void alTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            String fe = alTxt.getText();
            int largo = fe.length();
            if (largo == 10) {
                try {
                    al = sdf.parse(alTxt.getText());
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "ERROR 252");
                    return;
                }
                cuitTxt.requestFocus();
            } else {
                if (largo > 10) {
                    JOptionPane.showMessageDialog(this, "ERROR EN LARGO DE FECHA");
                    return;
                }
            }
            fe = UtilFrame.fecha(fe);
            alTxt.setText(fe);
        }
    }//GEN-LAST:event_alTxtKeyPressed

    private void cuitTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuitTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!cuitTxt.getText().isEmpty()) {
                buscarFcPorCuit();
            } else {
                buscarFcEntreFechas();
            }
        }
    }//GEN-LAST:event_cuitTxtKeyPressed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        volver();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void pdfFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfFacturaBtnActionPerformed
        pdf();
    }//GEN-LAST:event_pdfFacturaBtnActionPerformed

    private void pdfListadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfListadoBtnActionPerformed
        pdfListado();
    }//GEN-LAST:event_pdfListadoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformesImpresosFacturasMpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformesImpresosFacturasMpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformesImpresosFacturasMpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformesImpresosFacturasMpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformesImpresosFacturasMpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alTxt;
    private javax.swing.JTextField cuitTxt;
    private javax.swing.JTextField deTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pdfFacturaBtn;
    private javax.swing.JButton pdfListadoBtn;
    private javax.swing.JTable tabla;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        deTxt.setText("");
        alTxt.setText("");
        cuitTxt.setText("");
        UtilFrame.limpiarTabla(tabla);
    }

    private void buscarFcPorCuit() {
        String filtro = cuitTxt.getText();
        int largo = filtro.length();
        if (largo != 13) {
            JOptionPane.showMessageDialog(this, "ERROR EN CUIT VERIFIQUE LOS GUIONES");
            return;
        }
        facturas = null;
        try {
            facturas = new FacturaCompraReferenciaMercadoPagoService()
                    .getFacturasIvaVentasEntreFechasAndCuit(de, al, filtro);
        } catch (Exception ex) {
            return;
        }
        llenarTabla();
    }

    private void buscarFcEntreFechas() {
        facturas = null;
//        System.out.println(de);
//        System.out.println(al);
//        System.exit(0);
        try {
            facturas = new FacturaCompraReferenciaMercadoPagoService()
                    .getFacturasIvaVentasEntreFechas(de, al);
        } catch (Exception ex) {
            return;
        }
        llenarTabla();
    }

    private void llenarTabla() {
        UtilFrame.limpiarTabla(tabla);
        if (facturas != null && !facturas.isEmpty()) {
//            Date fecha = facturas.get(0).getIvaVentas().getFecha();
//            Double totalNetoGravadoDia = 0.0;
//            Double totalImpuestoDia = 0.0;
//            Double totalIvaDia = 0.0;
            Double totalDia = 0.0;

//            Double totalNetoGravado = 0.0;
//            Double totalImpuesto = 0.0;
//            Double totalIva = 0.0;
//            Double total = 0.0;
            DefaultTableModel tbl = (DefaultTableModel) tabla.getModel();
            for (FacturaCompraReferenciaMercadoPago fcmp : facturas) {
                IvaVentas iv = fcmp.getIvaVentas();
                Date fecha2 = iv.getFecha();
                String cuit = iv.getCliente().getCuit();
                String nombre = iv.getCliente().getRazonSocial();
                String origen = fcmp.getCompraClienteMercadoPago().getOrigen();
                Double total = iv.getTotal();
                Date ff = iv.getFecha();
                Integer nro = iv.getNumeroFactura();
//                if (fecha.equals(fecha2)) {
//                    totalNetoGravadoDia += fcmp.getIvaVentas().getGravado();
//                    totalImpuestoDia += fcmp.getIvaVentas().getImpuesto();
//                    totalIvaDia += fcmp.getIvaVentas().getIva();
//                    totalDia += fcmp.getIvaVentas().getTotal();
//                } else {
                Object o[] = new Object[7];
                o[0] = sdf.format(fecha2);
                o[1] = cuit;
                o[2] = nombre;
                o[3] = df.format(total);
                o[4] = origen;
                o[5] = sdf.format(ff);
                o[6] = nro;
//                    o[1] = df.format(totalNetoGravadoDia);
//                    o[2] = df.format(totalImpuestoDia);;
//                    o[3] = df.format(totalIvaDia);
                
                tbl.addRow(o);
//                totalNetoGravadoDia += fcmp.getIvaVentas().getGravado();
//                totalImpuestoDia += fcmp.getIvaVentas().getImpuesto();
//                totalIvaDia += fcmp.getIvaVentas().getIva();
                totalDia += fcmp.getIvaVentas().getTotal();
//                    fecha = fecha2;
//                }
//                totalNetoGravado += fcmp.getIvaVentas().getGravado();
//                totalImpuesto += fcmp.getIvaVentas().getImpuesto();
//                totalIva += fcmp.getIvaVentas().getIva();
//                total += fcmp.getIvaVentas().getTotal();
            }
//            Object o[] = new Object[5];
//            o[0] = sdf.format(fecha);
//            o[1] = df.format(totalNetoGravadoDia);
//            o[2] = df.format(totalImpuestoDia);
//            o[3] = df.format(totalIvaDia);
//            o[4] = df.format(totalDia);
//            tbl.addRow(o);
            Object o1[] = new Object[7];
            o1[0] = "TOTAL >>";
//            o1[1] = df.format(totalNetoGravado);
//            o1[2] = df.format(totalImpuesto);
//            o1[3] = df.format(totalIva);
            o1[3] = df.format(totalDia);
            tbl.addRow(o1);
            tabla.setModel(tbl);
        }
    }

    private void volver() {
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }

    private void pdf() {
        int row = tabla.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "SELECCIONE UNA PARA IMPRIMIR");
            return;
        }
        if (tabla.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "SELECCIONE SOLO UNA PARA IMPRIMIR");
            return;
        }
        IvaVentas iv = facturas.get(row).getIvaVentas();
        List<RenglonFactura> rf = null;
        try {
            rf = new RenglonFacturaService().getAllRenglonFacturaFromIvaVentas(iv);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR 452");
            return;
        }

        if (rf != null && !rf.isEmpty()) {
            pdf(iv, rf);
//            volver();
//            JOptionPane.showMessageDialog(this, "PROCESO TERMINADO");
        }
    }

    private void pdf(IvaVentas iv, List<RenglonFactura> rf) {
        String letra = iv.getLetra();
        Integer sucursal = iv.getNumeroSucursal();
        fecha_qr = sdf_qr.format(iv.getFecha());
        String cui = iv.getCliente().getCuit();
        String pri = "";
        String med = "";
        String fin = "";
        int lgo = cui.length();
        if (lgo != 13) {
            cui = "0000000000000" + cui;
            int lgo1 = cui.length();
            fin = cui.substring(lgo1 - 11, lgo1);
        }
        if (lgo > 11) {
            if (cui.equals("00-00000000-0")) {
                pri = "0";
                med = "";
                fin = "";
            } else {
                pri = cui.substring(0, 2);
                med = cui.substring(3, 11);
                fin = cui.substring(12, 13);
            }
        }
        numeroDoc_qr = pri + med + fin;
        puntoVenta_qr = sucursal.toString();
        tipoComprobante_qr = iv.getTipoDoc().toString();
        numeroComprobante_qr = iv.getNumeroFactura().toString();
        String nc = df_matriz.format(iv.getNumeroFactura());
        importe_qr = df.format(iv.getTotal()).replace(",", ".");
        tipoDoc_qr = iv.getCliente().getTipo();
        nroCae_qr = iv.getCae().toString();
//        nroCae_qr = pri + med + fin;
        String data = "{\"ver\"" + ":" + ver_qr
                + ",\"fecha\"" + ":" + "\"" + fecha_qr + "\""
                + ",\"cuit\"" + ":" + cuit_qr
                + ",\"ptoVta\"" + ":" + puntoVenta_qr
                + ",\"tipoCmp\"" + ":" + tipoComprobante_qr
                + ",\"nroCmp\"" + ":" + numeroComprobante_qr
                + ",\"importe\"" + ":" + importe_qr
                + ",\"moneda\"" + ":\"" + moneda_qr + "\""
                + ",\"ctz\"" + ":" + cotiz_qr
                + ",\"tipoDocRec\"" + ":" + tipoDoc_qr
                + ",\"nroDocRec\"" + ":" + numeroDoc_qr
                + ",\"tipoCodAut\"" + ":\"" + tipoCodigoAutoriz_qr + "\""
                + ",\"codAut\"" + ":" + nroCae_qr + "}";
        System.out.println(data);
//        System.exit(0);
        try {
            generarQR(data, nc);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR 536");
            return;
        }
        if (letra.equals("B")) {
            try {
                File pdf = new PDFBuilder().armarFacturaB(iv, rf);
                DesktopApi.open(pdf);
                JOptionPane.showMessageDialog(this, "PROCESO TERMINADO");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "ERROR 556");
            } catch (DocumentException ex) {
                JOptionPane.showMessageDialog(this, "ERROR 557");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR 558");
            }
        }
    }

    private void generarQR(String data, String numeroFactura) throws Exception {
        String cadenaCodificada = Base64.getEncoder().encodeToString(data.getBytes());
        BitMatrix matriz;
        Writer writer = new QRCodeWriter();
        try {
            matriz = writer.encode(url_qr + cadenaCodificada, BarcodeFormat.QR_CODE, qrTamAncho, qrTamAlto);
        } catch (WriterException e) {
            e.printStackTrace(System.err);
            JOptionPane.showMessageDialog(this, "ERROR GENERANDO QR");
            return;
        }
        BufferedImage imagen = new BufferedImage(qrTamAncho,
                qrTamAlto, BufferedImage.TYPE_INT_RGB);
        for (int y = 0; y < qrTamAlto; y++) {
            for (int x = 0; x < qrTamAncho; x++) {
                int valor = (matriz.get(x, y) ? 0 : 1) & 0xff;
                imagen.setRGB(x, y, (valor == 0 ? 0 : 0xFFFFFF));
            }
        }
        //99
        FileOutputStream qrCode;
        //String nf_qr = numeroFactura;
        qrCode = new FileOutputStream(ruta + numeroFactura + extension);
        ImageIO.write(imagen, formato, qrCode);
        qrCode.close();

    }

    private void pdfListado() {
        if (facturas != null && !facturas.isEmpty()) {
            try {
                File pdf = new PDFBuilder().listadoFacturas(facturas);
                DesktopApi.open(pdf);
                JOptionPane.showMessageDialog(this, "PROCESO TERMINADO");
            } catch (DocumentException ex) {
                JOptionPane.showMessageDialog(this, "ERROR Nro. 604");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR Nro. 605");
            }
        }
    }
}
