package com.ventas.frame;

import com.ventas.entities.Configuracion;
import com.ventas.entities.Producto;
import com.ventas.entities.ProductoTop;
import com.ventas.services.ConfiguracionService;
import com.ventas.services.ProductoService;
import com.ventas.services.ProductoTopService;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class NuevoProductoTopFrame extends javax.swing.JFrame {

    private Producto producto = null;
    private List<Producto> productos = null;
    private DecimalFormat df = new DecimalFormat("#0.00");

    /**
     * Creates new form NuevoProductoTopFrame
     */
    public NuevoProductoTopFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 100, 255));
        this.setLocationRelativeTo(null);
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        filtroTxt = new javax.swing.JTextField();
        v = new javax.swing.JButton();
        comboProductos = new javax.swing.JComboBox<>();
        agregarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cantidadMaximaTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        precioTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantidadMinimaTxt = new javax.swing.JTextField();
        porcentualCantidadMaximaVentaTxt = new javax.swing.JTextField();
        ventaSinStockChk = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        fraccionTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        netoTxt = new javax.swing.JTextField();
        impuestoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fraccionMpTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("NUEVO PRODUCTO UTILIZADO");

        jLabel2.setText("Nombre:");

        filtroTxt.setText("BUSCAR");
        filtroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroTxtKeyPressed(evt);
            }
        });

        v.setText("Volver");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        comboProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });
        comboProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboProductosKeyPressed(evt);
            }
        });

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        agregarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarBtnKeyPressed(evt);
            }
        });

        jLabel3.setText("Cantidad Máxima Venta:");

        cantidadMaximaTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadMaximaTxt.setText("CAN MAX");
        cantidadMaximaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadMaximaTxtKeyPressed(evt);
            }
        });

        jLabel4.setText("Final c/Iva:");

        precioTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precioTxt.setText("FINAL");

        jLabel7.setText("Porcentual Cantidad Máxima Venta Automática:");

        jLabel8.setText("Cantidad Mínima Venta:");

        cantidadMinimaTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidadMinimaTxt.setText("CAN MIN");
        cantidadMinimaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadMinimaTxtKeyPressed(evt);
            }
        });

        porcentualCantidadMaximaVentaTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        porcentualCantidadMaximaVentaTxt.setText("POR");
        porcentualCantidadMaximaVentaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                porcentualCantidadMaximaVentaTxtKeyPressed(evt);
            }
        });

        ventaSinStockChk.setText("Venta sin Stock");

        jLabel10.setText("Fracción por Importe:");

        fraccionTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fraccionTxt.setText("FR.MIN:vta");
        fraccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fraccionTxtKeyPressed(evt);
            }
        });

        jLabel11.setText("Neto:");

        jLabel12.setText("Impuesto:");

        netoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        netoTxt.setText("NETO");

        impuestoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        impuestoTxt.setText("IMPUESTO");

        jLabel1.setText("Fracción Mercado Pago:");

        fraccionMpTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fraccionMpTxt.setText("FRAC2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboProductos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(filtroTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(259, 259, 259)
                            .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(porcentualCantidadMaximaVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cantidadMinimaTxt)
                                        .addComponent(cantidadMaximaTxt)
                                        .addComponent(fraccionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addComponent(fraccionMpTxt))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel4))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(jLabel12)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(113, 113, 113)
                                            .addComponent(jLabel11)))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(netoTxt))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(v)
                                    .addComponent(ventaSinStockChk))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filtroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cantidadMinimaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(netoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadMaximaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(impuestoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fraccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fraccionMpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(porcentualCantidadMaximaVentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventaSinStockChk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v)
                    .addComponent(agregarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtroTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!filtroTxt.getText().isEmpty()) {
                String filtro = filtroTxt.getText();
                productos = null;
                try {
                    productos = new ProductoService().getAllProductosOrdenadoByNombre(filtro);
                } catch (Exception ex) {
                    Logger.getLogger(NuevoProductoTopFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (productos != null && !productos.isEmpty()) {
                    for (Producto p : productos) {
                        comboProductos.addItem(p.getDetalle());
                    }
                    comboProductos.requestFocus();
                    comboProductos.addFocusListener(null);
                    comboProductos.showPopup();
                }
            }
        }
    }//GEN-LAST:event_filtroTxtKeyPressed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
        if (evt.getModifiers() == 16) {
            buscarProducto();

        }
    }//GEN-LAST:event_comboProductosActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        AbmProductosTopFrame aptf = new AbmProductosTopFrame();
        aptf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        agregar();
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void comboProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboProductosKeyPressed
        if (evt.getKeyCode() == 10) {
            buscarProducto();
        }
    }//GEN-LAST:event_comboProductosKeyPressed

    private void agregarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarBtnKeyPressed
        if (evt.getKeyCode() == 10) {
            agregar();
        }
    }//GEN-LAST:event_agregarBtnKeyPressed

    private void cantidadMaximaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadMaximaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!cantidadMaximaTxt.getText().isEmpty()) {
                fraccionTxt.requestFocus();

            }
        }
    }//GEN-LAST:event_cantidadMaximaTxtKeyPressed

    private void cantidadMinimaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadMinimaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!cantidadMinimaTxt.getText().isEmpty()) {
                Integer frac = Integer.valueOf(cantidadMinimaTxt.getText().replace(",", "."));
                fraccionTxt.setText(frac.toString());
                cantidadMaximaTxt.requestFocus();
            }
        }

    }//GEN-LAST:event_cantidadMinimaTxtKeyPressed

    private void porcentualCantidadMaximaVentaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porcentualCantidadMaximaVentaTxtKeyPressed
        if (evt.getKeyCode() == 10) {
            if (!porcentualCantidadMaximaVentaTxt.getText().isEmpty()) {
                agregar();
            }
        }
    }//GEN-LAST:event_porcentualCantidadMaximaVentaTxtKeyPressed

    private void fraccionTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fraccionTxtKeyPressed
        if(evt.getKeyCode()==10){
            if(!fraccionTxt.getText().isEmpty()){
                porcentualCantidadMaximaVentaTxt.requestFocus();
            }
        }
    }//GEN-LAST:event_fraccionTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoTopFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoTopFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoTopFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProductoTopFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProductoTopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField cantidadMaximaTxt;
    private javax.swing.JTextField cantidadMinimaTxt;
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JTextField filtroTxt;
    private javax.swing.JTextField fraccionMpTxt;
    private javax.swing.JTextField fraccionTxt;
    private javax.swing.JTextField impuestoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField netoTxt;
    private javax.swing.JTextField porcentualCantidadMaximaVentaTxt;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JButton v;
    private javax.swing.JCheckBox ventaSinStockChk;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        filtroTxt.setText("");
        precioTxt.setEditable(false);
        precioTxt.setText("");
        cantidadMaximaTxt.setText("");
        cantidadMinimaTxt.setText("");
        comboProductos.removeAllItems();
        comboProductos.addItem("");
        porcentualCantidadMaximaVentaTxt.setText("");
        filtroTxt.requestFocus();
        fraccionTxt.setText("");
        fraccionMpTxt.setText("");
    }

    private void buscarProducto() {
//        int cod = Integer.valueOf(codigoTxt.getText());
        producto = null;
        int row_x = comboProductos.getSelectedIndex();
        if (row_x > 0) {
            int row = comboProductos.getSelectedIndex();
            if (row < 1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un producto de la lista");
                return;
            }
            producto = productos.get(row - 1);

        }
        Configuracion co = null;
        try {
//            producto = new ProductoService().getProductoByCodigo(cod);
            co = new ConfiguracionService().getFacturas(1L);
        } catch (Exception ex) {
            Logger.getLogger(NuevoProductoTopFrame.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        Float iva = 0.0F;
        if (co != null) {
            iva = co.getIva() / 100;
        }
        if (producto != null) {
            Double precio = producto.getPrecio() + producto.getImpuesto() + (producto.getPrecio() * iva);
            Float impInt = producto.getImpuesto();
            Double neto = producto.getPrecio();
            netoTxt.setText(df.format(neto));
            impuestoTxt.setText(df.format(impInt));
            precioTxt.setText(df.format(precio));
        } else {
            JOptionPane.showMessageDialog(this, "NO EXISTE PRODUCTO");
            return;
        }
        cantidadMinimaTxt.requestFocus();
    }

    private void agregar() {
        int cod = producto.getCodigo();
        ProductoTop pt = null;
        try {
            pt = new ProductoTopService().getProductoTopByCodigo(cod);
        } catch (Exception ex) {
            // es válido para agregar
        }
        if (pt != null) {
            JOptionPane.showMessageDialog(this, "Producto existente");
            limpiarCampos();
        } else {
            ProductoTop proEsta = null;
            try {
                proEsta = new ProductoTopService().getProductoTopByCodigo(cod);
            } catch (Exception ex) {
                // es válido para agregar
            }
            if (proEsta != null) {
                JOptionPane.showMessageDialog(this, "Producto existente");
                limpiarCampos();
                return;
            }
            ProductoTop pro = new ProductoTop();
            pro.setActivo(true);
            pro.setCodigo(cod);
            pro.setOrden(0);
            pro.setPanificado(false);
            Integer cantMax = Integer.valueOf(cantidadMaximaTxt.getText());
            Integer cantMin = Integer.valueOf(cantidadMinimaTxt.getText().replace(",", "."));
            Integer fraccion = Integer.valueOf(fraccionTxt.getText().replace(",", "."));
            Integer fraccionMp = Integer.valueOf(fraccionMpTxt.getText().replace(",", "."));
            if(fraccion > cantMin){
                JOptionPane.showMessageDialog(this, "Verifique fracción y Mínimo venta");
                return;
            }
            pro.setCantidadMaximaVenta(cantMax);
            pro.setCantidadMinimaVenta(cantMin);
            pro.setFraccion(fraccion);
            pro.setFraccionMp(fraccionMp);
            pro.setStock(producto.getStock());
            pro.setDetalle(producto.getDetalle());
            pro.setUsado(false);
            pro.setImpuesto(producto.getImpuesto());
            pro.setPrecio(producto.getPrecio());
            pro.setRubro(producto.getRubro());
            pro.setSubRubro(producto.getSubRubro());
            Float porcentual = Float.valueOf(porcentualCantidadMaximaVentaTxt.getText().replace(",", "."));
            pro.setPorcentualMaximoVentaAutomatica(porcentual);
            try {
                new ProductoTopService().saveProductoTop(pro);
            } catch (Exception ex) {
                Logger.getLogger(NuevoProductoTopFrame.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Producto agregado correctamente");
            limpiarCampos();
        }
    }
}
