package com.ventas.frame;

import com.ventas.entities.ProductoTop;
import com.ventas.entities.Rubro;
import com.ventas.services.ProductoTopService;
import com.ventas.services.RubroService;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author argia
 */
public class TstFrame extends javax.swing.JFrame {

    private List<Rubro> rubros = null;
    private Rubro rubro;
    private Float porIva = .21F;
    private Integer ordenMax;

    /**
     * Creates new form TstFrame
     */
    public TstFrame() {
        initComponents();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leerRndBtn = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        habilitarBtn = new javax.swing.JButton();
        minTxt = new javax.swing.JTextField();
        maxTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generarEntreBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leerRndBtn.setText("Leer Rnd");
        leerRndBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerRndBtnActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        habilitarBtn.setText("Habilitar");
        habilitarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarBtnActionPerformed(evt);
            }
        });

        minTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minTxt.setText("MIN");

        maxTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxTxt.setText("MAX");

        jLabel1.setText("MIN");

        jLabel2.setText("MAX");

        generarEntreBtn.setText("Generar entre");
        generarEntreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarEntreBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        totalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTxt.setText("TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leerRndBtn)
                            .addComponent(habilitarBtn))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo, 0, 301, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generarEntreBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(minTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(maxTxt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(leerRndBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habilitarBtn)
                    .addComponent(generarEntreBtn))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerRndBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerRndBtnActionPerformed
        leerRnd();
    }//GEN-LAST:event_leerRndBtnActionPerformed

    private void habilitarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarBtnActionPerformed
        habilitar();
    }//GEN-LAST:event_habilitarBtnActionPerformed

    private void generarEntreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarEntreBtnActionPerformed
        generarEntre();
    }//GEN-LAST:event_generarEntreBtnActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        int row = combo.getSelectedIndex();
        if (row > 0) {
            List<ProductoTop> pts;
            try {
                pts = new ProductoTopService().getAllProductoTabacoTopActivos9(rubro);
            } catch (Exception ex) {
                return;
            }
            ordenMax = pts.get(0).getOrden();
        }
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton generarEntreBtn;
    private javax.swing.JButton habilitarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton leerRndBtn;
    private javax.swing.JTextField maxTxt;
    private javax.swing.JTextField minTxt;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables

    private void leerRnd() {
        if (hayMas()) {
            Float ord;
            Random rnd1 = new Random();
            List<ProductoTop> productos = new ArrayList<>();
            Boolean otro = true;
            do {
                ProductoTop pt = null;
                ord = rnd1.nextFloat() * 19 + .5f;
                Integer orden = ord.intValue();
                try {
                    pt = new ProductoTopService().getProductoTopByOrder(orden);
                } catch (Exception ex) {
                    Logger.getLogger(TstFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (!pt.getUsado()) {
                    if (pt.getStock() > 0) {
                        productos.add(pt);
                        pt.setUsado(true);
                        pt.setStock(pt.getStock() - pt.getFraccion());
                        try {
                            new ProductoTopService().updateProductoTop(pt);
                        } catch (Exception ex) {
                            Logger.getLogger(TstFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                try {
                    new ProductoTopService().updateProductoTop(pt);
                } catch (Exception ex) {
                    Logger.getLogger(TstFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                otro = hayMas();
            } while (otro);
            for (int i = 0; i < productos.size(); i++) {
                ProductoTop prx = productos.get(i);
                System.out.print(prx.getCodigo());
                System.out.print(" ");
                Double precio = prx.getPrecio() * (1 + porIva / 100) + prx.getImpuesto();
                Double precioFinal = precio * prx.getFraccion();
                System.out.print(" ");
                System.out.print(precioFinal);
                System.out.print(" ");
                System.out.println(productos.get(i).getDetalle());
            }
        } else {
            System.out.println("NO HAY PARA GENERAR");
        }
    }

    private Boolean hayMas() {
        int row = combo.getSelectedIndex() - 1;
        Rubro ru = rubros.get(row);
        Boolean hay = false;
        List<ProductoTop> prod = null;
        try {
            prod = new ProductoTopService().getAllProductoTabacoTopActivos9(ru);
        } catch (Exception ex) {
            Logger.getLogger(TstFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (ProductoTop pt2 : prod) {
            if (!pt2.getUsado()) {
                hay = true;
                break;
            }
        }
        return hay;
    }

    private void llenarCombo() {
        rubros = null;
        try {
            rubros = new RubroService().getAllRubros();
        } catch (Exception ex) {
            Logger.getLogger(TstFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        combo.removeAllItems();
        combo.addItem("");
        rubros.forEach((r) -> {
            combo.addItem(r.getNombre());
        });

    }

    private void habilitar() {
        int row = combo.getSelectedIndex() - 1;
        Rubro ru = rubros.get(row);
        List<ProductoTop> prod = null;
        try {
            prod = new ProductoTopService().getAllProductoTabacoTopActivos9(ru);
        } catch (Exception ex) {
            Logger.getLogger(TstFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (ProductoTop pt2 : prod) {
            pt2.setUsado(false);
            try {
                new ProductoTopService().updateProductoTop(pt2);
            } catch (Exception ex) {
                System.out.println("ERROR 245");
                System.exit(0);
            }
        }
        System.out.println("HABILITACION FINALIZADA");
    }

    private void generarEntre() {
        Double minimo = Double.valueOf(minTxt.getText());
        Double maximo = Double.valueOf(maxTxt.getText());
        Integer cantidad = generarCantidad2a6();
        ProductoTop productoTop = generarImporteEntreMinAndMax(minimo, maximo, cantidad);

    }

    private Integer generarCantidad2a6() {
        Integer cantidad;
        do {
            Random rndC = new Random();
            Float can = rndC.nextFloat() * 6 + 1;
            cantidad = can.intValue();
        } while (cantidad < 7);
        return cantidad;
    }

    private ProductoTop generarImporteEntreMinAndMax(Double minimo, Double maximo, Integer cantidad) {
        Double importe;
        ProductoTop proT;
        do {
            proT = generarProductoTop();
            if (cantidad > proT.getStock()) {
                cantidad = proT.getStock().intValue();
            }
            importe = calcularTotalLinea(proT, cantidad);
            if (importe >= minimo && importe <= maximo) {

            }
        } while (importe >= minimo && importe <= maximo);
        return proT;
    }

    private ProductoTop generarProductoTop() {
        Random rndPT = new Random();
        ProductoTop pt = null;
        if (hayMas()) {
            Float ordn = rndPT.nextFloat();
            Integer orden = ordn.intValue();
            try {
                pt = new ProductoTopService().getProductoTopByOrder(orden);
            } catch (Exception ex) {
                pt = null;
            }
        }
        return pt;
    }

    private Double calcularTotalLinea(ProductoTop proT, Integer cantidad) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
